# Generated by Django 5.2.8 on 2025-11-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('PBrand', models.CharField(max_length=30)),
                ('PID', models.CharField(max_length=10)),
                ('Product_MRP', models.CharField(max_length=12)),
                ('PType', models.CharField(max_length=15)),
                ('manuf_date', models.DateField()),
            ],
        ),
    ]
