# Generated by Django 5.2.8 on 2025-11-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='ProductName',
        ),
        migrations.AlterField(
            model_name='product',
            name='PBrand',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='product',
            name='PID',
            field=models.CharField(max_length=26),
        ),
    ]
